# Generated by Django 5.0.1 on 2024-01-08 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioAPP', '0002_alter_patient_addresse_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
