# Generated by Django 5.0.1 on 2024-01-10 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioAPP', '0003_alter_consultation_date_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
