# Generated by Django 4.0.4 on 2024-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioAPP', '0004_alter_consultation_date_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='resultat',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
